---
spring:
  application:
    name: bentfores-gateway

  cloud:
    gateway:
      filter:
        redirect-to:
          enabled: false
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - RemoveRequestHeader=Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origin-patterns:
              - http://localhost:3000
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowed-headers:
              - Authorization
              - Content-Type
              - X-Requested-With
              - Cookie
              - Content-Security-Policy
      routes:
        - id: management-route
          uri: http://localhost:8091
          predicates:
            - Path=/management/**
          filters:
            - RemoveRequestHeader=Forwarded
          metadata:
            cors:
              allowedOriginPatterns:
                - http://localhost:3000
              allowedMethods:
                - GET
                - POST
                - PATCH
                - PUT
                - OPTIONS
              allowedHeaders:
                - Authorization
                - Content-Type
                - X-Requested-With
                - Platform
                - Cookie

        - id: analysis-route
          uri: http://localhost:8091
          predicates:
            - Path=/analysis/**
          filters:
            - RemoveRequestHeader=Forwarded
          metadata:
            cors:
              allowedOriginPatterns:
                - http://localhost:3000
              allowedMethods:
                - GET
                - POST
                - PATCH
                - PUT
                - OPTIONS
              allowedHeaders:
                - Authorization
                - Content-Type
                - X-Requested-With
                - Platform
                - Cookie

        - id: external-route
          uri: http://localhost:8091
          predicates:
            - Path=/external/**
          filters:
            - RemoveRequestHeader=Forwarded
          metadata:
            cors:
              allowedOriginPatterns:
                - http://localhost:3000
              allowedMethods:
                - GET
                - POST
                - PATCH
                - PUT
                - OPTIONS
              allowedHeaders:
                - Authorization
                - Content-Type
                - X-Requested-With
                - Platform
                - Cookie

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8443/realms/local
        registration:
          keycloak:
            client-id: gateway
            client-secret: secret
            redirect-uri: http://localhost:3000/not_processed
            authorization-grant-type: authorization_code
            scope: openid

logging:
  level:
    root: debug
